name: Vuong Do Thanh Huy
url: http://vuongdothanhhuy.github.io
description: My personal blog

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
